//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vehicles.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vehicles.Core.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make and model cannot be empty..
        /// </summary>
        public static string Error_MakeModelEmpty {
            get {
                return ResourceManager.GetString("Error_MakeModelEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Odometer cannot be negative..
        /// </summary>
        public static string Error_OdometerNegative {
            get {
                return ResourceManager.GetString("Error_OdometerNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distance must be greater than zero..
        /// </summary>
        public static string Error_Validation_DistanceMustBePositive {
            get {
                return ResourceManager.GetString("Error_Validation_DistanceMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amphibious Car {0} {1} drove {2} km on land. Total odometer: {3} km..
        /// </summary>
        public static string Log_AmphibiousDrove {
            get {
                return ResourceManager.GetString("Log_AmphibiousDrove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amphibious Car {0} {1} swam {2} km in water. Total odometer: {3} km..
        /// </summary>
        public static string Log_AmphibiousSwam {
            get {
                return ResourceManager.GetString("Log_AmphibiousSwam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Boat {0} {1} sailed {2} km. Total odometer: {3} km..
        /// </summary>
        public static string Log_BoatSailed {
            get {
                return ResourceManager.GetString("Log_BoatSailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car {0} {1} drove {2} km. Total odometer: {3} km..
        /// </summary>
        public static string Log_CarDrove {
            get {
                return ResourceManager.GetString("Log_CarDrove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} {1} flashes headlights as {2} {3} left!.
        /// </summary>
        public static string Log_VehicleFlashes {
            get {
                return ResourceManager.GetString("Log_VehicleFlashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} {1} honks as {2} {3} arrives!.
        /// </summary>
        public static string Log_VehicleHonks {
            get {
                return ResourceManager.GetString("Log_VehicleHonks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Validation Error.
        /// </summary>
        public static string UI_Error_ValidationTitle {
            get {
                return ResourceManager.GetString("UI_Error_ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string UI_ErrorTitle {
            get {
                return ResourceManager.GetString("UI_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid input! Please enter a valid number..
        /// </summary>
        public static string UI_InvalidInputMessage {
            get {
                return ResourceManager.GetString("UI_InvalidInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removed: {0} {1}.
        /// </summary>
        public static string UI_Log_VehicleRemoved {
            get {
                return ResourceManager.GetString("UI_Log_VehicleRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Odometer: {0} km.
        /// </summary>
        public static string UI_OdometerFormat {
            get {
                return ResourceManager.GetString("UI_OdometerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a vehicle from the list.
        /// </summary>
        public static string UI_SelectVehiclePrompt {
            get {
                return ResourceManager.GetString("UI_SelectVehiclePrompt", resourceCulture);
            }
        }
    }
}
